FROM node:22-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm install
RUN ./node_modules/.bin/prisma generate
EXPOSE 3000
CMD ["npm", "run", "dev"]