FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm install
RUN ./node_modules/.bin/prisma generate --schema=prisma/schema.prisma
EXPOSE 3000
CMD ["npm", "run", "dev"]